name: pipeline

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GITHUBTOKEN:
        required: true 
      SNYK_TOKEN:
        required: true 
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

  push:
    branches:   
      - main
      - develop 

jobs:
  
  security_sast:
    uses: ./.github/workflows/security_sast.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  deploy_to_aws:
    uses: ./.github/workflows/deploy.yml
    needs: security_sast
    secrets:
      GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  security_dast:
    uses: ./.github/workflows/security_dast.yml
    needs: deploy_to_aws ## Para que corra DAST necesita tener Deploy AWS
    secrets:
      GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}     
